### ISSUE TITLE
immediate crash on OSX El Cap

### ISSUE THREAD

**Issue by gvoysey** [dmnfarrell/pandastable#38] opened 2016-03-23 13:33 UTC
(unrelated to #37 as far as I know)

Running python 3.5.1 on OSX El Cap (10.11.3).   I have multiple versions of python installed, all using homebrew (so `which python3` returns `/usr/local/bin/python3` and `which python` returns `/usr/local/bin/python`).  

`pip install pandastable` executes cleanly. 

at a command prompt, this crash occurs.  I examined the contents of `/usr/local/bin/dataexplore` and modified the first line to point at the right python3 location, to no change. 
``` bash
gvoysey@host % dataexplore
/usr/local/lib/python3.5/site-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
2016-03-23 09:25:46.856 Python[40618:8434553] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fd83376bd90
2016-03-23 09:25:46.858 Python[40618:8434553] An uncaught exception was raised
2016-03-23 09:25:46.858 Python[40618:8434553] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fd83376bd90
2016-03-23 09:25:46.858 Python[40618:8434553] (
	0   CoreFoundation                      0x00007fff93588ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8960173c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9358bb9d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff934c4601 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff934c4188 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x00000001107a1958 TkpInit + 476
	6   Tk                                  0x000000011071ca7e Tk_Init + 1799
	7   _tkinter.cpython-35m-darwin.so      0x00000001105fbd6a Tcl_AppInit + 82
	8   _tkinter.cpython-35m-darwin.so      0x00000001105f731e _tkinter_create + 1112
	9   Python                              0x000000010f7c4ae9 PyCFunction_Call + 273
	10  Python                              0x000000010f8282eb PyEval_EvalFrameEx + 22399
	11  Python                              0x000000010f82b770 _PyEval_EvalCodeWithName + 1884
	12  Python                              0x000000010f822b57 PyEval_EvalCodeEx + 78
	13  Python                              0x000000010f7adcc3 function_call + 377
	14  Python                              0x000000010f78c1de PyObject_Call + 97
	15  Python                              0x000000010f79e8f0 method_call + 140
	16  Python                              0x000000010f78c1de PyObject_Call + 97
	17  Python                              0x000000010f7d6a7e slot_tp_init + 57
	18  Python                              0x000000010f7d3e03 type_call + 171
	19  Python                              0x000000010f78c1de PyObject_Call + 97
	20  Python                              0x000000010f828047 PyEval_EvalFrameEx + 21723
	21  Python                              0x000000010f82b770 _PyEval_EvalCodeWithName + 1884
	22  Python                              0x000000010f82c0af fast_function + 341
	23  Python                              0x000000010f828180 PyEval_EvalFrameEx + 22036
	24  Python                              0x000000010f82b770 _PyEval_EvalCodeWithName + 1884
	25  Python                              0x000000010f82c0af fast_function + 341
	26  Python                              0x000000010f828180 PyEval_EvalFrameEx + 22036
	27  Python                              0x000000010f82b770 _PyEval_EvalCodeWithName + 1884
	28  Python                              0x000000010f82c0af fast_function + 341
	29  Python                              0x000000010f828180 PyEval_EvalFrameEx + 22036
	30  Python                              0x000000010f82b770 _PyEval_EvalCodeWithName + 1884
	31  Python                              0x000000010f822b57 PyEval_EvalCodeEx + 78
	32  Python                              0x000000010f7adcc3 function_call + 377
	33  Python                              0x000000010f78c1de PyObject_Call + 97
	34  Python                              0x000000010f79e8f0 method_call + 140
	35  Python                              0x000000010f78c1de PyObject_Call + 97
	36  Python                              0x000000010f7d6a7e slot_tp_init + 57
	37  Python                              0x000000010f7d3e03 type_call + 171
	38  Python                              0x000000010f78c1de PyObject_Call + 97
	39  Python                              0x000000010f828047 PyEval_EvalFrameEx + 21723
	40  Python                              0x000000010f82c02f fast_function + 213
	41  Python                              0x000000010f828180 PyEval_EvalFrameEx + 22036
	42  Python                              0x000000010f82b770 _PyEval_EvalCodeWithName + 1884
	43  Python                              0x000000010f822b03 PyEval_EvalCode + 81
	44  Python                              0x000000010f8484d9 run_mod + 58
	45  Python                              0x000000010f8487ba PyRun_FileExFlags + 178
	46  Python                              0x000000010f847e0e PyRun_SimpleFileExFlags + 469
	47  Python                              0x000000010f85bd92 Py_Main + 3342
	48  Python                              0x000000010f77ee27 Python + 7719
	49  libdyld.dylib                       0x00007fff9ccef5ad start + 1
	50  ???                                 0x0000000000000002 0x0 + 2
)
2016-03-23 09:25:46.859 Python[40618:8434553] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fd83376bd90'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff93588ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8960173c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9358bb9d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff934c4601 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff934c4188 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x00000001107a1958 TkpInit + 476
	6   Tk                                  0x000000011071ca7e Tk_Init + 1799
	7   _tkinter.cpython-35m-darwin.so      0x00000001105fbd6a Tcl_AppInit + 82
	8   _tkinter.cpython-35m-darwin.so      0x00000001105f731e _tkinter_create + 1112
	9   Python                              0x000000010f7c4ae9 PyCFunction_Call + 273
	10  Python                              0x000000010f8282eb PyEval_EvalFrameEx + 22399
	11  Python                              0x000000010f82b770 _PyEval_EvalCodeWithName + 1884
	12  Python                              0x000000010f822b57 PyEval_EvalCodeEx + 78
	13  Python                              0x000000010f7adcc3 function_call + 377
	14  Python                              0x000000010f78c1de PyObject_Call + 97
	15  Python                              0x000000010f79e8f0 method_call + 140
	16  Python                              0x000000010f78c1de PyObject_Call + 97
	17  Python                              0x000000010f7d6a7e slot_tp_init + 57
	18  Python                              0x000000010f7d3e03 type_call + 171
	19  Python                              0x000000010f78c1de PyObject_Call + 97
	20  Python                              0x000000010f828047 PyEval_EvalFrameEx + 21723
	21  Python                              0x000000010f82b770 _PyEval_EvalCodeWithName + 1884
	22  Python                              0x000000010f82c0af fast_function + 341
	23  Python                              0x000000010f828180 PyEval_EvalFrameEx + 22036
	24  Python                              0x000000010f82b770 _PyEval_EvalCodeWithName + 1884
	25  Python                              0x000000010f82c0af fast_function + 341
	26  Python                              0x000000010f828180 PyEval_EvalFrameEx + 22036
	27  Python                              0x000000010f82b770 _PyEval_EvalCodeWithName + 1884
	28  Python                              0x000000010f82c0af fast_function + 341
	29  Python                              0x000000010f828180 PyEval_EvalFrameEx + 22036
	30  Python                              0x000000010f82b770 _PyEval_EvalCodeWithName + 1884
	31  Python                              0x000000010f822b57 PyEval_EvalCodeEx + 78
	32  Python                              0x000000010f7adcc3 function_call + 377
	33  Python                              0x000000010f78c1de PyObject_Call + 97
	34  Python                              0x000000010f79e8f0 method_call + 140
	35  Python                              0x000000010f78c1de PyObject_Call + 97
	36  Python                              0x000000010f7d6a7e slot_tp_init + 57
	37  Python                              0x000000010f7d3e03 type_call + 171
	38  Python                              0x000000010f78c1de PyObject_Call + 97
	39  Python                              0x000000010f828047 PyEval_EvalFrameEx + 21723
	40  Python                              0x000000010f82c02f fast_function + 213
	41  Python                              0x000000010f828180 PyEval_EvalFrameEx + 22036
	42  Python                              0x000000010f82b770 _PyEval_EvalCodeWithName + 1884
	43  Python                              0x000000010f822b03 PyEval_EvalCode + 81
	44  Python                              0x000000010f8484d9 run_mod + 58
	45  Python                              0x000000010f8487ba PyRun_FileExFlags + 178
	46  Python                              0x000000010f847e0e PyRun_SimpleFileExFlags + 469
	47  Python                              0x000000010f85bd92 Py_Main + 3342
	48  Python                              0x000000010f77ee27 Python + 7719
	49  libdyld.dylib                       0x00007fff9ccef5ad start + 1
	50  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
zsh: abort      dataexplore
```

**Comment by gvoysey** [comment] 2016-03-23 13:37
here's my `pip list` : 

```
appnope (0.1.0)
blessings (1.6)
bokeh (0.10.0)
cycler (0.10.0)
decorator (4.0.6)
docopt (0.6.2)
Flask (0.10.1)
gnureadline (6.3.3)
ipykernel (4.2.1)
ipython (4.0.1)
ipython-genutils (0.1.0)
ipywidgets (4.1.1)
itsdangerous (0.24)
Jinja2 (2.8)
jsonpickle (0.9.2)
jsonschema (2.5.1)
jupyter-client (4.1.1)
jupyter-core (4.0.6)
MarkupSafe (0.23)
matplotlib (1.5.1)
mistune (0.7.1)
nbconvert (4.1.0)
nbformat (4.0.1)
notebook (4.0.6)
numexpr (2.5)
numpy (1.10.2)
pandas (0.17.1)
pandastable (0.7.1)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.5)
pip (8.1.1)
progressbar2 (3.6.0)
ptyprocess (0.5)
Pygments (2.0.2)
pyparsing (2.1.0)
python-dateutil (2.4.2)
pytz (2015.7)
PyYAML (3.11)
pyzmq (15.1.0)
qtconsole (4.1.1)
requests (2.9.1)
scipy (0.17.0)
seaborn (0.7.0)
setuptools (18.3.1)
simplegeneric (0.8.1)
six (1.10.0)
terminado (0.5)
tornado (4.3)
traitlets (4.0.0)
Werkzeug (0.11.3)
wheel (0.26.0)
xlrd (0.9.4)
```

**Comment by dmnfarrell** [comment] 2016-03-23 14:39
I don't have access to a mac so can't test it on OSX. However I have added a -t option to the dataexplore command to open a simple test table without the plot frame. This will tell you if matplotlib is the problem. This will be in version 0.7.2 which I'll upload soon.
Or you could put the code shown in the wiki into a script and try it - https://github.com/dmnfarrell/pandastable/wiki/Code-Examples

**Comment by dmnfarrell** [comment] 2016-03-25 15:04
v0.7.2 is now on pypi so could you install that and try to launch it with dataexplore -t without the plot frame.

**Comment by gvoysey** [comment] 2016-03-25 15:16
no joy. 

``` bash
gvoysey@host % dataexplore -t
2016-03-25 11:15:48.682 Python[90874:9701342] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7f8a5339b5a0
2016-03-25 11:15:48.686 Python[90874:9701342] An uncaught exception was raised
2016-03-25 11:15:48.686 Python[90874:9701342] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7f8a5339b5a0
2016-03-25 11:15:48.687 Python[90874:9701342] (
	0   CoreFoundation                      0x00007fff93588ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8960173c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9358bb9d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff934c4601 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff934c4188 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x000000010f380958 TkpInit + 476
	6   Tk                                  0x000000010f2fba7e Tk_Init + 1799
	7   _tkinter.cpython-35m-darwin.so      0x000000010f1dad6a Tcl_AppInit + 82
	8   _tkinter.cpython-35m-darwin.so      0x000000010f1d631e _tkinter_create + 1112
	9   Python                              0x000000010e3a7ae9 PyCFunction_Call + 273
	10  Python                              0x000000010e40b2eb PyEval_EvalFrameEx + 22399
	11  Python                              0x000000010e40e770 _PyEval_EvalCodeWithName + 1884
	12  Python                              0x000000010e405b57 PyEval_EvalCodeEx + 78
	13  Python                              0x000000010e390cc3 function_call + 377
	14  Python                              0x000000010e36f1de PyObject_Call + 97
	15  Python                              0x000000010e3818f0 method_call + 140
	16  Python                              0x000000010e36f1de PyObject_Call + 97
	17  Python                              0x000000010e3b9a7e slot_tp_init + 57
	18  Python                              0x000000010e3b6e03 type_call + 171
	19  Python                              0x000000010e36f1de PyObject_Call + 97
	20  Python                              0x000000010e40b047 PyEval_EvalFrameEx + 21723
	21  Python                              0x000000010e40e770 _PyEval_EvalCodeWithName + 1884
	22  Python                              0x000000010e40f0af fast_function + 341
	23  Python                              0x000000010e40b180 PyEval_EvalFrameEx + 22036
	24  Python                              0x000000010e40e770 _PyEval_EvalCodeWithName + 1884
	25  Python                              0x000000010e40f0af fast_function + 341
	26  Python                              0x000000010e40b180 PyEval_EvalFrameEx + 22036
	27  Python                              0x000000010e40e770 _PyEval_EvalCodeWithName + 1884
	28  Python                              0x000000010e40f0af fast_function + 341
	29  Python                              0x000000010e40b180 PyEval_EvalFrameEx + 22036
	30  Python                              0x000000010e40e770 _PyEval_EvalCodeWithName + 1884
	31  Python                              0x000000010e405b57 PyEval_EvalCodeEx + 78
	32  Python                              0x000000010e390cc3 function_call + 377
	33  Python                              0x000000010e36f1de PyObject_Call + 97
	34  Python                              0x000000010e3818f0 method_call + 140
	35  Python                              0x000000010e36f1de PyObject_Call + 97
	36  Python                              0x000000010e3b9a7e slot_tp_init + 57
	37  Python                              0x000000010e3b6e03 type_call + 171
	38  Python                              0x000000010e36f1de PyObject_Call + 97
	39  Python                              0x000000010e40b047 PyEval_EvalFrameEx + 21723
	40  Python                              0x000000010e40f02f fast_function + 213
	41  Python                              0x000000010e40b180 PyEval_EvalFrameEx + 22036
	42  Python                              0x000000010e40e770 _PyEval_EvalCodeWithName + 1884
	43  Python                              0x000000010e405b03 PyEval_EvalCode + 81
	44  Python                              0x000000010e42b4d9 run_mod + 58
	45  Python                              0x000000010e42b7ba PyRun_FileExFlags + 178
	46  Python                              0x000000010e42ae0e PyRun_SimpleFileExFlags + 469
	47  Python                              0x000000010e43ed92 Py_Main + 3342
	48  Python                              0x000000010e35de27 Python + 7719
	49  libdyld.dylib                       0x00007fff9ccef5ad start + 1
	50  ???                                 0x0000000000000003 0x0 + 3
)
2016-03-25 11:15:48.687 Python[90874:9701342] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7f8a5339b5a0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff93588ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8960173c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9358bb9d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff934c4601 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff934c4188 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x000000010f380958 TkpInit + 476
	6   Tk                                  0x000000010f2fba7e Tk_Init + 1799
	7   _tkinter.cpython-35m-darwin.so      0x000000010f1dad6a Tcl_AppInit + 82
	8   _tkinter.cpython-35m-darwin.so      0x000000010f1d631e _tkinter_create + 1112
	9   Python                              0x000000010e3a7ae9 PyCFunction_Call + 273
	10  Python                              0x000000010e40b2eb PyEval_EvalFrameEx + 22399
	11  Python                              0x000000010e40e770 _PyEval_EvalCodeWithName + 1884
	12  Python                              0x000000010e405b57 PyEval_EvalCodeEx + 78
	13  Python                              0x000000010e390cc3 function_call + 377
	14  Python                              0x000000010e36f1de PyObject_Call + 97
	15  Python                              0x000000010e3818f0 method_call + 140
	16  Python                              0x000000010e36f1de PyObject_Call + 97
	17  Python                              0x000000010e3b9a7e slot_tp_init + 57
	18  Python                              0x000000010e3b6e03 type_call + 171
	19  Python                              0x000000010e36f1de PyObject_Call + 97
	20  Python                              0x000000010e40b047 PyEval_EvalFrameEx + 21723
	21  Python                              0x000000010e40e770 _PyEval_EvalCodeWithName + 1884
	22  Python                              0x000000010e40f0af fast_function + 341
	23  Python                              0x000000010e40b180 PyEval_EvalFrameEx + 22036
	24  Python                              0x000000010e40e770 _PyEval_EvalCodeWithName + 1884
	25  Python                              0x000000010e40f0af fast_function + 341
	26  Python                              0x000000010e40b180 PyEval_EvalFrameEx + 22036
	27  Python                              0x000000010e40e770 _PyEval_EvalCodeWithName + 1884
	28  Python                              0x000000010e40f0af fast_function + 341
	29  Python                              0x000000010e40b180 PyEval_EvalFrameEx + 22036
	30  Python                              0x000000010e40e770 _PyEval_EvalCodeWithName + 1884
	31  Python                              0x000000010e405b57 PyEval_EvalCodeEx + 78
	32  Python                              0x000000010e390cc3 function_call + 377
	33  Python                              0x000000010e36f1de PyObject_Call + 97
	34  Python                              0x000000010e3818f0 method_call + 140
	35  Python                              0x000000010e36f1de PyObject_Call + 97
	36  Python                              0x000000010e3b9a7e slot_tp_init + 57
	37  Python                              0x000000010e3b6e03 type_call + 171
	38  Python                              0x000000010e36f1de PyObject_Call + 97
	39  Python                              0x000000010e40b047 PyEval_EvalFrameEx + 21723
	40  Python                              0x000000010e40f02f fast_function + 213
	41  Python                              0x000000010e40b180 PyEval_EvalFrameEx + 22036
	42  Python                              0x000000010e40e770 _PyEval_EvalCodeWithName + 1884
	43  Python                              0x000000010e405b03 PyEval_EvalCode + 81
	44  Python                              0x000000010e42b4d9 run_mod + 58
	45  Python                              0x000000010e42b7ba PyRun_FileExFlags + 178
	46  Python                              0x000000010e42ae0e PyRun_SimpleFileExFlags + 469
	47  Python                              0x000000010e43ed92 Py_Main + 3342
	48  Python                              0x000000010e35de27 Python + 7719
	49  libdyld.dylib                       0x00007fff9ccef5ad start + 1
	50  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
zsh: abort      dataexplore -t
```

**Comment by dmnfarrell** [comment] 2016-03-25 15:20
Ok thanks.

**Comment by dantrep** [comment] 2016-05-07 20:57
I got the same exception as gvoysey.  However, I was able to get the app to run on a Mac by commenting out the .core import statement in the __init__.py file resulting in the following:

#from .core import *
from .data import *
__version__ = '0.7.2'

In trying to understand the problem, I found that if the .core import statement is left in the __init__.py file, the first attempt to create a Tkinter frame causes the exception. In digging further, I found that the problem lies somewhere with the import of pyplot within the plotting.py module:

import matplotlib.pyplot as plt

I'm not sure why that would be.  Everything works fine if you import the same module later in the sequence. Hopefully someone can figure out the cause.  Otherwise, it seems to work OK for now by commenting out the import in __init__.py.

**Comment by dantrep** [comment] 2016-05-07 21:25
Oh.  It's worth clarifying that I got the app to work by running it from a command line with the command:

python -m pandastable.app

I still can't import the module into my python code after a pip install. . .

**Closed** 2016-07-19 16:21 UTC

**Comment by jocago** [comment] 2017-01-30 21:21
Same problem as above. 
/Users/xxx/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
2017-01-30 16:19:01.542 python[84718:4858015] -[NSApplication _setup:]: unrecognized selector sent to instance 0x1020623d0
2017-01-30 16:19:01.544 python[84718:4858015] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x1020623d0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffb0babe7b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffc5795cad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffb0c2dcb4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fffb0b1dfb5 ___forwarding___ + 1061
	4   CoreFoundation                      0x00007fffb0b1db08 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x000000010245a5e6 TkpInit + 471
	6   Tk                                  0x00000001023d5c8d Tk_Init + 1794
	7   _tkinter.so                         0x00000001003f1144 Tcl_AppInit + 84
	8   _tkinter.so                         0x00000001003f0e39 _tkinter_create + 1129
	9   libpython3.5m.dylib                 0x000000010004ff38 PyCFunction_Call + 280
	10  libpython3.5m.dylib                 0x00000001000bd2df PyEval_EvalFrameEx + 22431
	11  libpython3.5m.dylib                 0x00000001000c10c3 _PyEval_EvalCodeWithName + 1779
	12  libpython3.5m.dylib                 0x00000001000b7b1e PyEval_EvalCodeEx + 78
	13  libpython3.5m.dylib                 0x000000010003430f function_call + 351
	14  libpython3.5m.dylib                 0x000000010000fd73 PyObject_Call + 99
	15  libpython3.5m.dylib                 0x000000010002130d method_call + 141
	16  libpython3.5m.dylib                 0x000000010000fd73 PyObject_Call + 99
	17  libpython3.5m.dylib                 0x0000000100065add slot_tp_init + 125
	18  libpython3.5m.dylib                 0x0000000100062329 type_call + 281
	19  libpython3.5m.dylib                 0x000000010000fd73 PyObject_Call + 99
	20  libpython3.5m.dylib                 0x00000001000bd766 PyEval_EvalFrameEx + 23590
	21  libpython3.5m.dylib                 0x00000001000c10c3 _PyEval_EvalCodeWithName + 1779
	22  libpython3.5m.dylib                 0x00000001000c19ae fast_function + 334
	23  libpython3.5m.dylib                 0x00000001000bd434 PyEval_EvalFrameEx + 22772
	24  libpython3.5m.dylib                 0x00000001000c10c3 _PyEval_EvalCodeWithName + 1779
	25  libpython3.5m.dylib                 0x00000001000c19ae fast_function + 334
	26  libpython3.5m.dylib                 0x00000001000bd434 PyEval_EvalFrameEx + 22772
	27  libpython3.5m.dylib                 0x00000001000c10c3 _PyEval_EvalCodeWithName + 1779
	28  libpython3.5m.dylib                 0x00000001000c19ae fast_function + 334
	29  libpython3.5m.dylib                 0x00000001000bd434 PyEval_EvalFrameEx + 22772
	30  libpython3.5m.dylib                 0x00000001000c10c3 _PyEval_EvalCodeWithName + 1779
	31  libpython3.5m.dylib                 0x00000001000b7b1e PyEval_EvalCodeEx + 78
	32  libpython3.5m.dylib                 0x000000010003430f function_call + 351
	33  libpython3.5m.dylib                 0x000000010000fd73 PyObject_Call + 99
	34  libpython3.5m.dylib                 0x000000010002130d method_call + 141
	35  libpython3.5m.dylib                 0x000000010000fd73 PyObject_Call + 99
	36  libpython3.5m.dylib                 0x0000000100065add slot_tp_init + 125
	37  libpython3.5m.dylib                 0x0000000100062329 type_call + 281
	38  libpython3.5m.dylib                 0x000000010000fd73 PyObject_Call + 99
	39  libpython3.5m.dylib                 0x00000001000bd766 PyEval_EvalFrameEx + 23590
	40  libpython3.5m.dylib                 0x00000001000c192f fast_function + 207
	41  libpython3.5m.dylib                 0x00000001000bd434 PyEval_EvalFrameEx + 22772
	42  libpython3.5m.dylib                 0x00000001000c10c3 _PyEval_EvalCodeWithName + 1779
	43  libpython3.5m.dylib                 0x00000001000b7ac1 PyEval_EvalCode + 81
	44  libpython3.5m.dylib                 0x00000001000b52ab builtin_exec + 555
	45  libpython3.5m.dylib                 0x000000010004ff38 PyCFunction_Call + 280
	46  libpython3.5m.dylib                 0x00000001000bd2df PyEval_EvalFrameEx + 22431
	47  libpython3.5m.dylib                 0x00000001000c10c3 _PyEval_EvalCodeWithName + 1779
	48  libpython3.5m.dylib                 0x00000001000c19ae fast_function + 334
	49  libpython3.5m.dylib                 0x00000001000bd434 PyEval_EvalFrameEx + 22772
	50  libpython3.5m.dylib                 0x00000001000c10c3 _PyEval_EvalCodeWithName + 1779
	51  libpython3.5m.dylib                 0x00000001000b7b1e PyEval_EvalCodeEx + 78
	52  libpython3.5m.dylib                 0x000000010003430f function_call + 351
	53  libpython3.5m.dylib                 0x000000010000fd73 PyObject_Call + 99
	54  libpython3.5m.dylib                 0x00000001000fce83 RunModule + 147
	55  libpython3.5m.dylib                 0x00000001000fc8c3 Py_Main + 2435
	56  python                              0x0000000100000dc7 main + 215
	57  python                              0x0000000100000ce4 start + 52
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by dmnfarrell** [comment] 2017-01-30 21:34
Did you try the fix suggested by dantrep of commenting out the first import in init.py. It's not possible for me to replicate the error as I have no access to OS X. I was hoping it would resolve itself with newer versions of matplotlib.

**Comment by jocago** [comment] 2017-01-30 21:51
It did. Though now I'm getting a different error when importing a CSV. I'll post that seperately. I'll also put a little time into trying to track down the problem with .core.
